#!/bin/sh
cd ..
git clone --recursive https://github.com/open-source-parsers/jsoncpp.git jsoncpp
cd jsoncpp
git pull
python amalgamate.py
cp -R dist/json ..
cp dist/jsoncpp.cpp ../json

# maybe you need to patch:
# src/json/jsoncpp.cpp:
# -#include <json/json.h>
# +#include "json/json.h"

#svn export --force https://jsoncpp.svn.sourceforge.net/svnroot/jsoncpp/trunk/jsoncpp/src/lib_json json
#svn export --force https://jsoncpp.svn.sourceforge.net/svnroot/jsoncpp/trunk/jsoncpp/include/json json
