#include "arnis_adapter.h"

namespace arnis
{

namespace block_definitions
{

Block ACACIA_PLANKS;
Block AIR;
Block ANDESITE;
Block BIRCH_LEAVES;
Block BIRCH_LOG;
Block BLACK_CONCRETE;
Block BLACKSTONE;
Block BLUE_FLOWER;
Block BLUE_TERRACOTTA;
Block BRICK;
Block CAULDRON;
Block CHISELED_STONE_BRICKS;
Block COBBLESTONE_WALL;
Block COBBLESTONE;
Block POLISHED_BLACKSTONE_BRICKS;
Block CRACKED_STONE_BRICKS;
Block CRIMSON_PLANKS;
Block CUT_SANDSTONE;
Block CYAN_CONCRETE;
Block DARK_OAK_PLANKS;
Block DEEPSLATE_BRICKS;
Block DIORITE;
Block DIRT;
Block END_STONE_BRICKS;
Block FARMLAND;
Block GLASS;
Block GLOWSTONE;
Block GRANITE;
Block GRASS_BLOCK;
Block GRASS;
Block GRAVEL;
Block GRAY_CONCRETE;
Block GRAY_TERRACOTTA;
Block GREEN_STAINED_HARDENED_CLAY;
Block GREEN_WOOL;
Block HAY_BALE;
Block IRON_BARS;
Block IRON_BLOCK;
Block JUNGLE_PLANKS;
Block LADDER;
Block LIGHT_BLUE_CONCRETE;
Block LIGHT_BLUE_TERRACOTTA;
Block LIGHT_GRAY_CONCRETE;
Block MOSS_BLOCK;
Block MOSSY_COBBLESTONE;
Block MUD_BRICKS;
Block NETHER_BRICK;
Block NETHERITE_BLOCK;
Block OAK_FENCE;
Block OAK_LEAVES;
Block OAK_LOG;
Block OAK_PLANKS;
Block OAK_SLAB;
Block ORANGE_TERRACOTTA;
Block PODZOL;
Block POLISHED_ANDESITE;
Block POLISHED_BASALT;
Block QUARTZ_BLOCK;
Block POLISHED_BLACKSTONE;
Block POLISHED_DEEPSLATE;
Block POLISHED_DIORITE;
Block POLISHED_GRANITE;
Block PRISMARINE;
Block PURPUR_BLOCK;
Block PURPUR_PILLAR;
Block QUARTZ_BRICKS;
Block RAIL;
Block RED_FLOWER;
Block RED_NETHER_BRICK;
Block RED_TERRACOTTA;
Block RED_WOOL;
Block SAND;
Block SANDSTONE;
Block SCAFFOLDING;
Block SMOOTH_QUARTZ;
Block SMOOTH_RED_SANDSTONE;
Block SMOOTH_SANDSTONE;
Block SMOOTH_STONE;
Block SPONGE;
Block SPRUCE_LOG;
Block SPRUCE_PLANKS;
Block STONE_BLOCK_SLAB;
Block STONE_BRICK_SLAB;
Block STONE_BRICKS;
Block STONE;
Block TERRACOTTA;
Block WARPED_PLANKS;
Block WATER;
Block WHITE_CONCRETE;
Block WHITE_FLOWER;
Block WHITE_STAINED_GLASS;
Block WHITE_TERRACOTTA;
Block WHITE_WOOL;
Block YELLOW_CONCRETE;
Block YELLOW_FLOWER;
Block YELLOW_WOOL;
Block LIME_CONCRETE;
Block CYAN_WOOL;
Block BLUE_CONCRETE;
Block PURPLE_CONCRETE;
Block RED_CONCRETE;
Block MAGENTA_CONCRETE;
Block BROWN_WOOL;
Block OXIDIZED_COPPER;
Block YELLOW_TERRACOTTA;
Block SNOW_BLOCK;
Block SNOW_LAYER;
Block SIGN;
Block ANDESITE_WALL;
Block STONE_BRICK_WALL;
Block CARROTS;
Block DARK_OAK_DOOR_LOWER;
Block DARK_OAK_DOOR_UPPER;
Block POTATOES;
Block WHEAT;
Block BEDROCK;
Block RAIL_NORTH_SOUTH;
Block RAIL_EAST_WEST;
Block RAIL_ASCENDING_EAST;
Block RAIL_ASCENDING_WEST;
Block RAIL_ASCENDING_NORTH;
Block RAIL_ASCENDING_SOUTH;
Block RAIL_NORTH_EAST;
Block RAIL_NORTH_WEST;
Block RAIL_SOUTH_EAST;
Block RAIL_SOUTH_WEST;
Block COARSE_DIRT;
Block IRON_ORE;
Block COAL_ORE;
Block GOLD_ORE;
Block COPPER_ORE;
Block CLAY;
Block DIRT_PATH;
Block ICE;
Block PACKED_ICE;
Block MUD;
Block DEAD_BUSH;
Block TALL_GRASS_BOTTOM;
Block TALL_GRASS_TOP;
Block CRAFTING_TABLE;
Block FURNACE;
Block WHITE_CARPET;
Block BOOKSHELF;
Block OAK_PRESSURE_PLATE;
Block OAK_STAIRS;
Block CHEST;
Block RED_CARPET;
Block ANVIL;
Block NOTE_BLOCK;
Block OAK_DOOR;
Block BREWING_STAND;
Block RED_BED_NORTH_HEAD;
Block RED_BED_NORTH_FOOT;
Block RED_BED_EAST_HEAD;
Block RED_BED_EAST_FOOT;
Block RED_BED_SOUTH_HEAD;
Block RED_BED_SOUTH_FOOT;
Block RED_BED_WEST_HEAD;
Block RED_BED_WEST_FOOT;
Block GRAY_STAINED_GLASS;
Block LIGHT_GRAY_STAINED_GLASS;
Block BROWN_STAINED_GLASS;
Block TINTED_GLASS;
Block OAK_TRAPDOOR;
Block BROWN_CONCRETE;
Block BLACK_TERRACOTTA;
Block BROWN_TERRACOTTA;
Block STONE_BRICK_STAIRS;
Block MUD_BRICK_STAIRS;
Block POLISHED_BLACKSTONE_BRICK_STAIRS;
Block BRICK_STAIRS;
Block POLISHED_GRANITE_STAIRS;
Block END_STONE_BRICK_STAIRS;
Block POLISHED_DIORITE_STAIRS;
Block SMOOTH_SANDSTONE_STAIRS;
Block QUARTZ_STAIRS;
Block POLISHED_ANDESITE_STAIRS;
Block NETHER_BRICK_STAIRS;

Block &SMOOTH_STONE_BLOCK = SMOOTH_STONE;
}

bool inited = false;
void init(MapgenEarth *mg)
{
	if (inited) {
		return;
	}
	inited = true;

	const auto def = mg->m_emerge->ndef->getId("default:cobble");

	const auto g = [&](const auto &v) {
		const auto id = mg->m_emerge->ndef->getId(v);
		if (id == CONTENT_IGNORE) {
			DUMP("Mapping node not found", v);
			return def;
		}
		return id;
	};

	ACACIA_PLANKS = g("default:wood");
	AIR = CONTENT_AIR;
	ANDESITE = def;
	BIRCH_LEAVES = g("default:leaves");
	BIRCH_LOG = g("default:tree");
	BLACK_CONCRETE = def;
	BLACKSTONE = def;
	BLUE_FLOWER = g("flowers:geranium");
	BLUE_TERRACOTTA = def;
	BRICK = g("default:brick");
	CAULDRON = def;
	CHISELED_STONE_BRICKS = def;
	COBBLESTONE_WALL = g("default:cobble");
	COBBLESTONE = g("default:cobble");
	POLISHED_BLACKSTONE_BRICKS = def;
	CRACKED_STONE_BRICKS = def;
	CRIMSON_PLANKS = g("default:wood");
	CUT_SANDSTONE = g("default:sandstone");
	CYAN_CONCRETE = def;
	DARK_OAK_PLANKS = g("default:wood");
	DEEPSLATE_BRICKS = def;
	DIORITE = def;
	DIRT = g("default:dirt");
	END_STONE_BRICKS = def;
	FARMLAND = g("default:dirt");
	GLASS = g("default:glass");
	GLOWSTONE = g("default:meselamp");
	GRANITE = def;
	GRASS_BLOCK = g("default:grass_5");
	GRASS = g("default:grass_3");
	GRAVEL = g("default:gravel");
	GRAY_CONCRETE = def;
	GRAY_TERRACOTTA = def;
	GREEN_STAINED_HARDENED_CLAY = def;
	GREEN_WOOL = g("wool:green");
	HAY_BALE = def;
	IRON_BARS = g("default:stone_with_iron");
	IRON_BLOCK = g("default:stone_with_iron");
	JUNGLE_PLANKS = g("default:wood");
	LADDER = g("default:ladder_wood");
	LIGHT_BLUE_CONCRETE = def;
	LIGHT_BLUE_TERRACOTTA = def;
	LIGHT_GRAY_CONCRETE = def;
	MOSS_BLOCK = def;
	MOSSY_COBBLESTONE = g("default:mossycobble");
	MUD_BRICKS = g("default:silver_sandstone_brick");
	NETHER_BRICK = g("default:obsidianbrick");
	NETHERITE_BLOCK = g("default:obsidian");
	OAK_FENCE = g("default:fence_wood");
	OAK_LEAVES = g("default:leaves");
	OAK_LOG = g("default:tree");
	OAK_PLANKS = g("default:wood");
	OAK_SLAB = g("stairs:slab_wood");
	ORANGE_TERRACOTTA = def;
	PODZOL = def;
	POLISHED_ANDESITE = def;
	POLISHED_BASALT = def;
	QUARTZ_BLOCK = def;
	POLISHED_BLACKSTONE = def;
	POLISHED_DEEPSLATE = def;
	POLISHED_DIORITE = def;
	POLISHED_GRANITE = def;
	PRISMARINE = def;
	PURPUR_BLOCK = def;
	PURPUR_PILLAR = def;
	QUARTZ_BRICKS = def;
	RAIL = g("default:rail");
	RED_FLOWER = g("flowers:tulip");
	RED_NETHER_BRICK = def;
	RED_TERRACOTTA = def;
	RED_WOOL = g("wool:red");
	SAND = g("default:sand");
	SANDSTONE = g("default:sandstone");
	SCAFFOLDING = g("default:ladder_steel");
	SMOOTH_QUARTZ = def;
	SMOOTH_RED_SANDSTONE = def;
	SMOOTH_SANDSTONE = def;
	SMOOTH_STONE = def;
	SPONGE = g("sponge:sponge");
	SPRUCE_LOG = def;
	SPRUCE_PLANKS = g("default:wood");
	STONE_BLOCK_SLAB = def;
	STONE_BRICK_SLAB = def;
	STONE_BRICKS = def;
	STONE = def;
	TERRACOTTA = def;
	WARPED_PLANKS = def;
	WATER = g("default:water_source");
	WHITE_CONCRETE = def;
	WHITE_FLOWER = g("flowers:dandelion_white");
	WHITE_STAINED_GLASS = GLASS;
	WHITE_TERRACOTTA = def;
	WHITE_WOOL = g("wool:white");
	YELLOW_CONCRETE = def;
	YELLOW_FLOWER = g("flowers:dandelion_yellow");
	YELLOW_WOOL = g("wool:yellow");
	LIME_CONCRETE = def;
	CYAN_WOOL = g("wool:cyan");
	BLUE_CONCRETE = def;
	PURPLE_CONCRETE = def;
	RED_CONCRETE = def;
	MAGENTA_CONCRETE = def;
	BROWN_WOOL = g("wool:brown");
	OXIDIZED_COPPER = def;
	YELLOW_TERRACOTTA = def;
	SNOW_BLOCK = g("default:snow");
	SNOW_LAYER = g("default:snow");
	SIGN = g("default:sign_wall");
	ANDESITE_WALL = def;
	STONE_BRICK_WALL = def;
	CARROTS = def;
	DARK_OAK_DOOR_LOWER = g("doors:door_wood_a");
	DARK_OAK_DOOR_UPPER = g("doors:door_wood_b");
	POTATOES = def;
	WHEAT = g("farming:wheat_4");
	BEDROCK = g("default:obsidian");
	RAIL_NORTH_SOUTH = RAIL;
	RAIL_EAST_WEST = RAIL;
	RAIL_ASCENDING_EAST = RAIL;
	RAIL_ASCENDING_WEST = RAIL;
	RAIL_ASCENDING_NORTH = RAIL;
	RAIL_ASCENDING_SOUTH = RAIL;
	RAIL_NORTH_EAST = RAIL;
	RAIL_NORTH_WEST = RAIL;
	RAIL_SOUTH_EAST = RAIL;
	RAIL_SOUTH_WEST = RAIL;
	COARSE_DIRT = g("default:dirt");
	IRON_ORE = g("default:stone_with_iron");
	COAL_ORE = g("default:stone_with_coal");
	GOLD_ORE = g("default:stone_with_gold");
	COPPER_ORE = g("default:stone_with_copper");
	CLAY = g("default:clay");
	DIRT_PATH = g("default:dirt");
	ICE = g("default:ice");
	PACKED_ICE = g("default:ice");
	MUD = g("default:dirt");
	DEAD_BUSH = g("default:bush_leaves"); //?
	TALL_GRASS_BOTTOM = g("default:grass_5");
	TALL_GRASS_TOP = g("default:grass_5");
	CRAFTING_TABLE = def;
	FURNACE = g("default:furnace");
	WHITE_CARPET = def;
	BOOKSHELF = g("default:bookshelf");
	OAK_PRESSURE_PLATE = def;
	OAK_STAIRS = g("stairs:stair_pine_wood");
	CHEST = g("default:chest");
	RED_CARPET = def;
	ANVIL = def;
	NOTE_BLOCK = def;
	OAK_DOOR = g("doors:door_wood_a");
	BREWING_STAND = def;
	RED_BED_NORTH_HEAD = g("beds:bed_top");
	RED_BED_NORTH_FOOT = g("beds:bed_bottom");
	RED_BED_EAST_HEAD = g("beds:bed_top");
	RED_BED_EAST_FOOT = g("beds:bed_bottom");
	RED_BED_SOUTH_HEAD = g("beds:bed_top");
	RED_BED_SOUTH_FOOT = g("beds:bed_bottom");
	RED_BED_WEST_HEAD = g("beds:bed_top");
	RED_BED_WEST_FOOT = g("beds:bed_bottom");
	GRAY_STAINED_GLASS = GLASS;
	LIGHT_GRAY_STAINED_GLASS = GLASS;
	BROWN_STAINED_GLASS = GLASS;
	TINTED_GLASS = GLASS;
	OAK_TRAPDOOR = g("doors:trapdoor");
	BROWN_CONCRETE = def;
	BLACK_TERRACOTTA = def;
	BROWN_TERRACOTTA = def;
	STONE_BRICK_STAIRS = g("stairs:stair_stonebrick");
	MUD_BRICK_STAIRS = STONE_BRICK_STAIRS;
	POLISHED_BLACKSTONE_BRICK_STAIRS = g("stairs:stair_obsidian_block");
	BRICK_STAIRS = g("stairs:stair_cobble");
	POLISHED_GRANITE_STAIRS = STONE_BRICK_STAIRS;
	END_STONE_BRICK_STAIRS = STONE_BRICK_STAIRS;
	POLISHED_DIORITE_STAIRS = STONE_BRICK_STAIRS;
	SMOOTH_SANDSTONE_STAIRS = g("stairs:stair_sandstone");
	QUARTZ_STAIRS = STONE_BRICK_STAIRS;
	POLISHED_ANDESITE_STAIRS = STONE_BRICK_STAIRS;
	NETHER_BRICK_STAIRS = STONE_BRICK_STAIRS;

	// TODO: find better in mods

	AIR = g("air");
	BLACK_CONCRETE = g("default:obsidian"); // ?
	BRICK = g("default:brick");
	COBBLESTONE = g("default:cobble");
	COBBLESTONE_WALL = g("default:cobble");
	DIRT = g("default:dirt");
	DIRT_PATH = g("default:dry_dirt");
	GLASS = g("default:glass");
	GLOWSTONE = g("default:stone");
	GRASS_BLOCK = g("default:dirt_with_grass");
	GRAVEL = g("default:gravel");
	GRAY_CONCRETE = g("default:stone"); //  TODO
	//GREEN_WOOL = g("wool:green");
	IRON_BLOCK = g("default:steelblock");	   // TODO
	LIGHT_GRAY_CONCRETE = g("default:cobble"); // TODO
	OAK_FENCE = g("default:wood");
	//OAK_FENCE_GATE = g("default:wood");
	//OAK_LEAVES = g("default:leaves");
	OAK_LOG = g("default:tree"); // TODO
	OAK_PLANKS = g("default:wood");
	//RAIL_EAST_WEST = g("default:rail");
	//RAIL_NORTH_EAST = g("default:rail");
	//RAIL_NORTH_SOUTH = g("default:rail");
	//RAIL_NORTH_WEST = g("default:rail");
	//RAIL_SOUTH_EAST = g("default:rail");
	//RAIL_SOUTH_WEST = g("default:rail");
	//RED_WOOL = g("wool:red");
	SAND = g("default:sand");
	SANDSTONE = g("default:sandstone");
	SMOOTH_STONE = g("default:stone");
	SMOOTH_STONE_BLOCK = g("default:stone"); //TODO
	SNOW_LAYER = g("default:snow");
	STONE = g("default:stone");
	STONE_BLOCK_SLAB = g("default:stone");
	STONE_BRICK_SLAB = g("default:cobble");
	STONE_BRICKS = g("default:cobble");
	WHITE_CONCRETE = g("default:stone");	  // TODO
	WHITE_STAINED_GLASS = g("default:glass"); // ?
	//WHITE_WOOL = g("wool:white");
	//YELLOW_WOOL = g("wool:yellow");
	//WATER = g("default:water");
}

}
