#include "arnis_adapter.h"
#include "emerge.h"

#include <initializer_list>

namespace arnis
{

namespace block_definitions
{

Block ACACIA_PLANKS;
Block AIR;
Block ANDESITE;
Block BIRCH_LEAVES;
Block BIRCH_LOG;
Block BLACK_CONCRETE;
Block BLACKSTONE;
Block BLUE_FLOWER;
Block BLUE_TERRACOTTA;
Block BRICK;
Block CAULDRON;
Block CHISELED_STONE_BRICKS;
Block COBBLESTONE_WALL;
Block COBBLESTONE;
Block POLISHED_BLACKSTONE_BRICKS;
Block CRACKED_STONE_BRICKS;
Block CRIMSON_PLANKS;
Block CUT_SANDSTONE;
Block CYAN_CONCRETE;
Block DARK_OAK_PLANKS;
Block DEEPSLATE_BRICKS;
Block DIORITE;
Block DIRT;
Block END_STONE_BRICKS;
Block FARMLAND;
Block GLASS;
Block GLOWSTONE;
Block GRANITE;
Block GRASS_BLOCK;
Block GRASS;
Block GRAVEL;
Block GRAY_CONCRETE;
Block GRAY_TERRACOTTA;
Block GREEN_STAINED_HARDENED_CLAY;
Block GREEN_WOOL;
Block HAY_BALE;
Block IRON_BARS;
Block IRON_BLOCK;
Block JUNGLE_PLANKS;
Block LADDER;
Block LIGHT_BLUE_CONCRETE;
Block LIGHT_BLUE_TERRACOTTA;
Block LIGHT_GRAY_CONCRETE;
Block MOSS_BLOCK;
Block MOSSY_COBBLESTONE;
Block MUD_BRICKS;
Block NETHER_BRICK;
Block NETHERITE_BLOCK;
Block OAK_FENCE;
Block OAK_LEAVES;
Block OAK_LOG;
Block OAK_PLANKS;
Block OAK_SLAB;
Block ORANGE_TERRACOTTA;
Block PODZOL;
Block POLISHED_ANDESITE;
Block POLISHED_BASALT;
Block QUARTZ_BLOCK;
Block POLISHED_BLACKSTONE;
Block POLISHED_DEEPSLATE;
Block POLISHED_DIORITE;
Block POLISHED_GRANITE;
Block PRISMARINE;
Block PURPUR_BLOCK;
Block PURPUR_PILLAR;
Block QUARTZ_BRICKS;
Block RAIL;
Block RED_FLOWER;
Block RED_NETHER_BRICK;
Block RED_TERRACOTTA;
Block RED_WOOL;
Block SAND;
Block SANDSTONE;
Block SCAFFOLDING;
Block SMOOTH_QUARTZ;
Block SMOOTH_RED_SANDSTONE;
Block SMOOTH_SANDSTONE;
Block SMOOTH_STONE;
Block SPONGE;
Block SPRUCE_LOG;
Block SPRUCE_PLANKS;
Block STONE_BLOCK_SLAB;
Block STONE_BRICK_SLAB;
Block STONE_BRICKS;
Block STONE;
Block TERRACOTTA;
Block WARPED_PLANKS;
Block WATER;
Block SEAGRASS;
Block KELP_PLANT;
Block MAGMA_BLOCK;
Block KELP;
Block TALL_SEAGRASS_BOTTOM;
Block TALL_SEAGRASS_TOP;
Block SEA_PICKLE;
Block SOUL_SAND;
Block WHITE_CONCRETE;
Block WHITE_FLOWER;
Block WHITE_STAINED_GLASS;
Block WHITE_TERRACOTTA;
Block WHITE_WOOL;
Block YELLOW_CONCRETE;
Block YELLOW_FLOWER;
Block YELLOW_WOOL;
Block LIME_CONCRETE;
Block CYAN_WOOL;
Block BLUE_CONCRETE;
Block PURPLE_CONCRETE;
Block RED_CONCRETE;
Block MAGENTA_CONCRETE;
Block BROWN_WOOL;
Block OXIDIZED_COPPER;
Block YELLOW_TERRACOTTA;
Block SNOW_BLOCK;
Block SNOW_LAYER;
Block SIGN;
Block ANDESITE_WALL;
Block STONE_BRICK_WALL;
Block CARROTS;
Block DARK_OAK_DOOR_LOWER;
Block DARK_OAK_DOOR_UPPER;
Block DARK_OAK_LOG;
Block DARK_OAK_LEAVES;
Block JUNGLE_LOG;
Block JUNGLE_LEAVES;
Block ACACIA_LOG;
Block ACACIA_LEAVES;
Block POTATOES;
Block WHEAT;
Block BEDROCK;
Block RAIL_NORTH_SOUTH;
Block RAIL_EAST_WEST;
Block RAIL_ASCENDING_EAST;
Block RAIL_ASCENDING_WEST;
Block RAIL_ASCENDING_NORTH;
Block RAIL_ASCENDING_SOUTH;
Block RAIL_NORTH_EAST;
Block RAIL_NORTH_WEST;
Block RAIL_SOUTH_EAST;
Block RAIL_SOUTH_WEST;
Block COARSE_DIRT;
Block IRON_ORE;
Block COAL_ORE;
Block GOLD_ORE;
Block COPPER_ORE;
Block CLAY;
Block DIRT_PATH;
Block ICE;
Block PACKED_ICE;
Block MUD;
Block DEAD_BUSH;
Block TALL_GRASS_BOTTOM;
Block TALL_GRASS_TOP;
Block CRAFTING_TABLE;
Block FURNACE;
Block WHITE_CARPET;
Block BOOKSHELF;
Block OAK_PRESSURE_PLATE;
Block OAK_STAIRS;
Block CHEST;
Block RED_CARPET;
Block ANVIL;
Block NOTE_BLOCK;
Block OAK_DOOR;
Block BREWING_STAND;
Block RED_BED_NORTH_HEAD;
Block RED_BED_NORTH_FOOT;
Block RED_BED_EAST_HEAD;
Block RED_BED_EAST_FOOT;
Block RED_BED_SOUTH_HEAD;
Block RED_BED_SOUTH_FOOT;
Block RED_BED_WEST_HEAD;
Block RED_BED_WEST_FOOT;
Block GRAY_STAINED_GLASS;
Block LIGHT_GRAY_STAINED_GLASS;
Block BROWN_STAINED_GLASS;
Block TINTED_GLASS;
Block OAK_TRAPDOOR;
Block BROWN_CONCRETE;
Block BLACK_TERRACOTTA;
Block BROWN_TERRACOTTA;
Block STONE_BRICK_STAIRS;
Block MUD_BRICK_STAIRS;
Block POLISHED_BLACKSTONE_BRICK_STAIRS;
Block BRICK_STAIRS;
Block POLISHED_GRANITE_STAIRS;
Block END_STONE_BRICK_STAIRS;
Block POLISHED_DIORITE_STAIRS;
Block SMOOTH_SANDSTONE_STAIRS;
Block QUARTZ_STAIRS;
Block POLISHED_ANDESITE_STAIRS;
Block NETHER_BRICK_STAIRS;

Block COBWEB;
Block CHISELLED_BOOKSHELF_NORTH; // Chiseled Bookshelf
Block CHISELLED_BOOKSHELF_EAST;	 // Chiseled Bookshelf East
Block CHISELLED_BOOKSHELF_SOUTH; // Chiseled Bookshelf South
Block CHISELLED_BOOKSHELF_WEST;	 // Chiseled Bookshelf West
Block DAMAGED_ANVIL;			 // Damaged Anvil

Block CHAIN;
Block END_ROD;
Block LIGHTNING_ROD;
Block GOLD_BLOCK;
Block SEA_LANTERN;
Block ORANGE_CONCRETE;
Block ORANGE_WOOL;
Block BLUE_WOOL;
Block GREEN_CONCRETE;
Block BRICK_WALL;
Block REDSTONE_BLOCK;
Block CHAIN_X;
Block CHAIN_Z;
Block SPRUCE_DOOR_LOWER;
Block SPRUCE_DOOR_UPPER;
Block SMOOTH_STONE_SLAB;
Block GLASS_PANE;
Block LIGHT_GRAY_TERRACOTTA;
Block OAK_SLAB_TOP;
Block OAK_DOOR_UPPER;
Block SPRUCE_LEAVES;
Block CYAN_STAINED_GLASS;
Block BLUE_STAINED_GLASS;
Block LIGHT_BLUE_STAINED_GLASS;
Block DAYLIGHT_DETECTOR;
Block RED_STAINED_GLASS;
Block YELLOW_STAINED_GLASS;
Block PURPLE_STAINED_GLASS;
Block ORANGE_STAINED_GLASS;
Block MAGENTA_STAINED_GLASS;
Block FLOWER_POT;
Block OAK_TRAPDOOR_OPEN_NORTH;
Block OAK_TRAPDOOR_OPEN_SOUTH;
Block OAK_TRAPDOOR_OPEN_EAST;
Block OAK_TRAPDOOR_OPEN_WEST;
Block QUARTZ_SLAB_TOP;
Block DARK_OAK_TRAPDOOR;
Block SPRUCE_TRAPDOOR;
Block BIRCH_TRAPDOOR;
Block MUD_BRICK_SLAB;
Block BRICK_SLAB;
Block POTTED_RED_TULIP;
Block POTTED_DANDELION;
Block POTTED_BLUE_ORCHID;
Block BARREL;
Block FERN;
Block CHIPPED_ANVIL;
Block LARGE_FERN_LOWER;
Block LARGE_FERN_UPPER;
Block LEVER;
Block COBBLESTONE_STAIRS;
Block WAXED_CUT_COPPER_STAIRS;
Block MOSSY_STONE_BRICK_STAIRS;
Block MOSSY_COBBLESTONE_STAIRS;
Block DEEPSLATE_BRICK_STAIRS;
Block POLISHED_DEEPSLATE_STAIRS;
Block RED_NETHER_BRICKS;
Block SPRUCE_STAIRS;
Block DARK_OAK_STAIRS;
Block RED_NETHER_BRICK_STAIRS;
Block WAXED_OXIDIZED_CUT_COPPER_STAIRS;
Block WAXED_OXIDIZED_COPPER;
Block ANDESITE_STAIRS;
Block WAXED_EXPOSED_CUT_COPPER_STAIRS;
Block WHITE_WALL_BANNER;
Block BLUE_WALL_BANNER;
Block BLACK_WALL_BANNER;
Block RED_WALL_BANNER;
Block GREEN_WALL_BANNER;
Block MOSSY_STONE_BRICKS;
Block DEEPSLATE;
Block TUFF;
Block COBBLED_DEEPSLATE;
Block WATER_CAULDRON;
Block WAXED_COPPER_BLOCK;
Block WAXED_EXPOSED_COPPER;
Block WAXED_EXPOSED_CHISELED_COPPER;
Block WAXED_EXPOSED_CUT_COPPER;
Block CHERRY_LOG;
Block CHERRY_LEAVES;
Block GRAY_CONCRETE_POWDER;
Block CYAN_TERRACOTTA;
Block BLACK_WOOL;
Block LIGHT_GRAY_WALL_BANNER;

Block &SMOOTH_STONE_BLOCK = SMOOTH_STONE;
}

bool inited = false;
void init(MapgenEarth *mg)
{
	if (inited) {
		return;
	}
	inited = true;

	const auto def = mg->m_emerge->ndef->getId("default:cobble");

	struct NodeResolver {
		MapgenEarth *mg;
		content_t fallback;

		content_t operator()(const char *name) const
		{
			const auto id = mg->m_emerge->ndef->getId(name);
			if (id == CONTENT_IGNORE) {
				DUMP("Mapping node not found", name);
				return fallback;
			}
			return id;
		}

		content_t operator()(std::initializer_list<const char *> names) const
		{
			for (const auto *name : names) {
				const auto id = mg->m_emerge->ndef->getId(name);
				if (id != CONTENT_IGNORE)
					return id;
			}
			if (names.size() > 0)
				DUMP("Mapping node alternatives not found", *names.begin());
			return fallback;
		}
	};
	const NodeResolver g{mg, def};

	ACACIA_PLANKS = g({"default:acacia_wood", "default:wood"});
	AIR = CONTENT_AIR;
	ANDESITE = g("default:stone");
	BIRCH_LEAVES = g({"default:aspen_leaves", "default:leaves"});
	BIRCH_LOG = g({"default:aspen_tree", "default:tree"});
	BLACK_CONCRETE = g({"wool:black", "basic_materials:concrete_block", "default:stone"});
	BLACKSTONE = g("default:obsidian");
	BLUE_FLOWER = g("flowers:geranium");
	BLUE_TERRACOTTA = g("default:clay");
	BRICK = g("default:brick");
	CAULDRON = g("default:steelblock");
	CHISELED_STONE_BRICKS = g("default:stonebrick");
	COBBLESTONE_WALL = g("default:cobble");
	COBBLESTONE = g("default:cobble");
	POLISHED_BLACKSTONE_BRICKS = g("default:obsidianbrick");
	CRACKED_STONE_BRICKS = g("default:stonebrick");
	CRIMSON_PLANKS = g("default:wood");
	CUT_SANDSTONE = g("default:sandstone");
	CYAN_CONCRETE = g({"wool:cyan", "basic_materials:concrete_block", "default:stone"});
	DARK_OAK_PLANKS = g({"default:wood", "default:junglewood"});
	DEEPSLATE_BRICKS = g("default:stonebrick");
	DIORITE = g("default:stone");
	DIRT = g("default:dirt");
	END_STONE_BRICKS = g("default:stonebrick");
	FARMLAND = g("default:dirt");
	GLASS = g("default:glass");
	GLOWSTONE = g("default:meselamp");
	GRANITE = g("default:stone");
	GRASS_BLOCK = g("default:grass_5");
	GRASS = g("default:grass_3");
	GRAVEL = g("default:gravel");
	GRAY_CONCRETE = g({"basic_materials:concrete_block", "wool:grey", "default:stone"});
	GRAY_TERRACOTTA = g("default:clay");
	GREEN_STAINED_HARDENED_CLAY = g("default:clay");
	GREEN_WOOL = g("wool:green");
	HAY_BALE = g("farming:straw");
	IRON_BARS = g({"xpanes:bar_flat", "default:steelblock", "default:stone_with_iron"});
	IRON_BLOCK = g("default:steelblock");
	JUNGLE_PLANKS = g({"default:junglewood", "default:wood"});
	LADDER = g("default:ladder_wood");
	LIGHT_BLUE_CONCRETE = g({"wool:cyan", "wool:blue", "basic_materials:concrete_block"});
	LIGHT_BLUE_TERRACOTTA = g("default:clay");
	LIGHT_GRAY_CONCRETE = g({"basic_materials:concrete_block", "wool:grey", "default:stone"});
	MOSS_BLOCK = g("default:mossycobble");
	MOSSY_COBBLESTONE = g("default:mossycobble");
	MUD_BRICKS = g("default:silver_sandstone_brick");
	NETHER_BRICK = g("default:obsidianbrick");
	NETHERITE_BLOCK = g("default:obsidian");
	OAK_FENCE = g("default:fence_wood");
	OAK_LEAVES = g("default:leaves");
	OAK_LOG = g("default:tree");
	OAK_PLANKS = g("default:wood");
	OAK_SLAB = g("stairs:slab_wood");
	ORANGE_TERRACOTTA = g("default:clay");
	PODZOL = g("default:dirt_with_coniferous_litter");
	POLISHED_ANDESITE = g("default:stone");
	POLISHED_BASALT = g("default:stone");
	QUARTZ_BLOCK = g("default:stone");
	POLISHED_BLACKSTONE = g({"default:obsidian", "default:stone"});
	POLISHED_DEEPSLATE = g("default:stone");
	POLISHED_DIORITE = g("default:stone");
	POLISHED_GRANITE = g("default:stone");
	PRISMARINE = g("default:stone");
	PURPUR_BLOCK = g("default:stone");
	PURPUR_PILLAR = g("default:stone");
	QUARTZ_BRICKS = g("default:stone");
	RAIL = g("default:rail");
	RED_FLOWER = g("flowers:tulip");
	RED_NETHER_BRICK = g("default:obsidianbrick");
	RED_TERRACOTTA = g("default:clay");
	RED_WOOL = g("wool:red");
	SAND = g("default:sand");
	SANDSTONE = g("default:sandstone");
	SCAFFOLDING = g("default:ladder_steel");
	SMOOTH_QUARTZ = g("default:stone");
	SMOOTH_RED_SANDSTONE = g("default:sandstone");
	SMOOTH_SANDSTONE = g("default:sandstone");
	SMOOTH_STONE = g("default:stone");
	SPONGE = g("sponge:sponge");
	SPRUCE_LOG = g({"default:pine_tree", "default:tree"});
	SPRUCE_PLANKS = g({"default:pine_wood", "default:wood"});
	STONE_BLOCK_SLAB = g({"stairs:slab_stone_block", "default:stone_block", "default:stone"});
	STONE_BRICK_SLAB = g({"stairs:slab_stonebrick", "default:stonebrick"});
	STONE_BRICKS = g("default:stonebrick");
	STONE = g("default:stone");
	TERRACOTTA = g("default:clay");
	WARPED_PLANKS = g("default:wood");
	WATER = g("default:water_source");
	// Rust parity: water_depth.rs uses MineClone ocean/nether blocks.
	// Divergence: Earth game maps them to available Minetest Game nodes.
	SEAGRASS = g({"default:marram_grass_1", "default:grass_3"});
	KELP_PLANT = g({"default:sand_with_kelp", "default:marram_grass_3", "default:marram_grass_1"});
	MAGMA_BLOCK = g({"default:obsidian", "default:lava_source", "default:stone"});
	KELP = KELP_PLANT;
	TALL_SEAGRASS_BOTTOM = g({"default:marram_grass_2", "default:marram_grass_1"});
	TALL_SEAGRASS_TOP = g({"default:marram_grass_3", "default:marram_grass_1"});
	SEA_PICKLE = g({"default:coral_green", "default:coral_cyan", "default:coral_skeleton"});
	SOUL_SAND = g({"default:desert_sand", "default:sand"});
	WHITE_CONCRETE = g({"wool:white", "basic_materials:concrete_block", "default:stone"});
	WHITE_FLOWER = g("flowers:dandelion_white");
	WHITE_STAINED_GLASS = GLASS;
	WHITE_TERRACOTTA = g("default:clay");
	WHITE_WOOL = g("wool:white");
	YELLOW_CONCRETE = g({"wool:yellow", "basic_materials:concrete_block", "default:stone"});
	YELLOW_FLOWER = g("flowers:dandelion_yellow");
	YELLOW_WOOL = g("wool:yellow");
	LIME_CONCRETE = g({"wool:green", "wool:yellow", "basic_materials:concrete_block"});
	CYAN_WOOL = g("wool:cyan");
	BLUE_CONCRETE = g({"wool:blue", "basic_materials:concrete_block", "default:stone"});
	PURPLE_CONCRETE = g({"wool:violet", "basic_materials:concrete_block", "default:stone"});
	RED_CONCRETE = g({"wool:red", "basic_materials:concrete_block", "default:stone"});
	MAGENTA_CONCRETE = g({"wool:magenta", "wool:violet", "basic_materials:concrete_block"});
	BROWN_WOOL = g("wool:brown");
	OXIDIZED_COPPER = g({"default:copperblock", "default:stone"});
	YELLOW_TERRACOTTA = g("default:clay");
	SNOW_BLOCK = g("default:snow");
	SNOW_LAYER = g("default:snow");
	SIGN = g({"default:sign_wall_wood", "default:sign_wall", "default:wood"});
	ANDESITE_WALL = g({"walls:cobble", "default:stone"});
	STONE_BRICK_WALL = g("default:stonebrick");
	CARROTS = g("farming:carrot_4");
	DARK_OAK_DOOR_LOWER = g("doors:door_wood_a");
	DARK_OAK_DOOR_UPPER = g("doors:door_wood_b");
	DARK_OAK_LOG = g({"default:tree", "default:jungletree"});
	DARK_OAK_LEAVES = g({"default:leaves", "default:jungleleaves"});
	JUNGLE_LOG = g({"default:jungletree", "default:tree"});
	JUNGLE_LEAVES = g({"default:jungleleaves", "default:leaves"});
	ACACIA_LOG = g({"default:acacia_tree", "default:tree"});
	ACACIA_LEAVES = g({"default:acacia_leaves", "default:leaves"});
	POTATOES = g("farming:potato_4");
	WHEAT = g("farming:wheat_4");
	BEDROCK = g("default:obsidian");
	RAIL_NORTH_SOUTH = RAIL;
	RAIL_EAST_WEST = RAIL;
	RAIL_ASCENDING_EAST = RAIL;
	RAIL_ASCENDING_WEST = RAIL;
	RAIL_ASCENDING_NORTH = RAIL;
	RAIL_ASCENDING_SOUTH = RAIL;
	RAIL_NORTH_EAST = RAIL;
	RAIL_NORTH_WEST = RAIL;
	RAIL_SOUTH_EAST = RAIL;
	RAIL_SOUTH_WEST = RAIL;
	COARSE_DIRT = g("default:dry_dirt");
	IRON_ORE = g("default:stone_with_iron");
	COAL_ORE = g("default:stone_with_coal");
	GOLD_ORE = g("default:stone_with_gold");
	COPPER_ORE = g("default:stone_with_copper");
	CLAY = g("default:clay");
	DIRT_PATH = g("default:dirt_with_grass_footsteps");
	ICE = g("default:ice");
	PACKED_ICE = g("default:ice");
	MUD = g("default:dirt");
	DEAD_BUSH = g("default:dry_shrub");
	TALL_GRASS_BOTTOM = g("default:grass_5");
	TALL_GRASS_TOP = g("default:grass_5");
	CRAFTING_TABLE = g("default:wood");
	FURNACE = g("default:furnace");
	WHITE_CARPET = g("wool:white");
	BOOKSHELF = g("default:bookshelf");
	OAK_PRESSURE_PLATE = g({"mesecons_pressureplates:pressure_plate_wood_off", "default:wood"});
	OAK_STAIRS = g({"stairs:stair_wood", "stairs:stair_pine_wood"});
	CHEST = g("default:chest");
	RED_CARPET = g("wool:red");
	ANVIL = g("default:steelblock");
	NOTE_BLOCK = g("default:wood");
	OAK_DOOR = g("doors:door_wood_a");
	BREWING_STAND = g("default:steelblock");
	RED_BED_NORTH_HEAD = g("beds:bed_top");
	RED_BED_NORTH_FOOT = g("beds:bed_bottom");
	RED_BED_EAST_HEAD = g("beds:bed_top");
	RED_BED_EAST_FOOT = g("beds:bed_bottom");
	RED_BED_SOUTH_HEAD = g("beds:bed_top");
	RED_BED_SOUTH_FOOT = g("beds:bed_bottom");
	RED_BED_WEST_HEAD = g("beds:bed_top");
	RED_BED_WEST_FOOT = g("beds:bed_bottom");
	GRAY_STAINED_GLASS = GLASS;
	LIGHT_GRAY_STAINED_GLASS = GLASS;
	BROWN_STAINED_GLASS = GLASS;
	TINTED_GLASS = GLASS;
	OAK_TRAPDOOR = g("doors:trapdoor");
	BROWN_CONCRETE = g({"wool:brown", "basic_materials:concrete_block", "default:stone"});
	BLACK_TERRACOTTA = g("default:clay");
	BROWN_TERRACOTTA = g("default:clay");
	STONE_BRICK_STAIRS = g("stairs:stair_stonebrick");
	MUD_BRICK_STAIRS = g({"stairs:stair_silver_sandstone_brick", "stairs:stair_stonebrick"});
	POLISHED_BLACKSTONE_BRICK_STAIRS = g({"stairs:stair_obsidianbrick", "stairs:stair_obsidian_block"});
	BRICK_STAIRS = g({"stairs:stair_brick", "stairs:stair_cobble"});
	POLISHED_GRANITE_STAIRS = STONE_BRICK_STAIRS;
	END_STONE_BRICK_STAIRS = STONE_BRICK_STAIRS;
	POLISHED_DIORITE_STAIRS = STONE_BRICK_STAIRS;
	SMOOTH_SANDSTONE_STAIRS = g("stairs:stair_sandstone");
	QUARTZ_STAIRS = STONE_BRICK_STAIRS;
	POLISHED_ANDESITE_STAIRS = STONE_BRICK_STAIRS;
	NETHER_BRICK_STAIRS = g({"stairs:stair_obsidianbrick", "stairs:stair_stonebrick"});

	COBWEB = g({"farming:cotton_wild", "xpanes:pane_flat", "default:glass"});
	CHISELLED_BOOKSHELF_NORTH = BOOKSHELF;
	CHISELLED_BOOKSHELF_EAST = BOOKSHELF;
	CHISELLED_BOOKSHELF_SOUTH = BOOKSHELF;
	CHISELLED_BOOKSHELF_WEST = BOOKSHELF;
	DAMAGED_ANVIL = ANVIL;

	CHAIN = g({"basic_materials:chain_steel", "xpanes:bar_flat", "default:steelblock"});
	END_ROD = GLOWSTONE;
	LIGHTNING_ROD = g({"default:copperblock", "basic_materials:brass_block", "default:steelblock"});
	GOLD_BLOCK = g("default:goldblock");
	SEA_LANTERN = GLOWSTONE;
	ORANGE_CONCRETE = g({"wool:orange", "basic_materials:concrete_block", "default:stone"});
	ORANGE_WOOL = g("wool:orange");
	BLUE_WOOL = g("wool:blue");
	GREEN_CONCRETE = g({"wool:green", "basic_materials:concrete_block", "default:stone"});
	BRICK_WALL = g("default:brick");
	REDSTONE_BLOCK = g("default:mese");
	CHAIN_X = CHAIN;
	CHAIN_Z = CHAIN;
	SPRUCE_DOOR_LOWER = OAK_DOOR;
	SPRUCE_DOOR_UPPER = OAK_DOOR;
	SMOOTH_STONE_SLAB = g({"stairs:slab_stone_block", "stairs:slab_stone", "default:stone"});
	GLASS_PANE = g({"xpanes:pane_flat", "default:glass"});
	LIGHT_GRAY_TERRACOTTA = g("default:clay");
	OAK_SLAB_TOP = OAK_SLAB;
	OAK_DOOR_UPPER = OAK_DOOR;
	SPRUCE_LEAVES = g({"default:pine_needles", "default:leaves"});
	CYAN_STAINED_GLASS = GLASS;
	BLUE_STAINED_GLASS = GLASS;
	LIGHT_BLUE_STAINED_GLASS = GLASS;
	DAYLIGHT_DETECTOR = g({"mesecons_solarpanel:solar_panel_off", "default:glass"});
	RED_STAINED_GLASS = GLASS;
	YELLOW_STAINED_GLASS = GLASS;
	PURPLE_STAINED_GLASS = GLASS;
	ORANGE_STAINED_GLASS = GLASS;
	MAGENTA_STAINED_GLASS = GLASS;
	FLOWER_POT = g("default:clay");
	OAK_TRAPDOOR_OPEN_NORTH = OAK_TRAPDOOR;
	OAK_TRAPDOOR_OPEN_SOUTH = OAK_TRAPDOOR;
	OAK_TRAPDOOR_OPEN_EAST = OAK_TRAPDOOR;
	OAK_TRAPDOOR_OPEN_WEST = OAK_TRAPDOOR;
	QUARTZ_SLAB_TOP = g("default:stone");
	DARK_OAK_TRAPDOOR = OAK_TRAPDOOR;
	SPRUCE_TRAPDOOR = OAK_TRAPDOOR;
	BIRCH_TRAPDOOR = OAK_TRAPDOOR;
	MUD_BRICK_SLAB = g({"stairs:slab_silver_sandstone_brick", "default:silver_sandstone_brick"});
	BRICK_SLAB = g({"stairs:slab_brick", "default:brick"});
	POTTED_RED_TULIP = g("flowers:rose");
	POTTED_DANDELION = g("flowers:dandelion_yellow");
	POTTED_BLUE_ORCHID = g("flowers:geranium");

	// Initialize missing blocks
	BARREL = g("default:chest");
	FERN = g("default:fern_3");
	CHIPPED_ANVIL = ANVIL;
	LARGE_FERN_LOWER = g("default:fern_2");
	LARGE_FERN_UPPER = g("default:fern_3");
	LEVER = g({"mesecons_walllever:wall_lever_off", "default:steelblock"});
	COBBLESTONE_STAIRS = g("stairs:stair_cobble");
	WAXED_CUT_COPPER_STAIRS = g({"stairs:stair_copperblock", "stairs:stair_stonebrick"});
	MOSSY_STONE_BRICK_STAIRS = g({"stairs:stair_mossycobble", "stairs:stair_stonebrick"});
	MOSSY_COBBLESTONE_STAIRS = g("stairs:stair_mossycobble");
	DEEPSLATE_BRICK_STAIRS = STONE_BRICK_STAIRS;
	POLISHED_DEEPSLATE_STAIRS = STONE_BRICK_STAIRS;
	RED_NETHER_BRICKS = NETHER_BRICK;
	SPRUCE_STAIRS = g("stairs:stair_pine_wood");
	DARK_OAK_STAIRS = OAK_STAIRS;
	RED_NETHER_BRICK_STAIRS = NETHER_BRICK_STAIRS;
	WAXED_OXIDIZED_CUT_COPPER_STAIRS = g({"stairs:stair_copperblock", "stairs:stair_stonebrick"});
	WAXED_OXIDIZED_COPPER = g({"default:copperblock", "default:stone"});
	ANDESITE_STAIRS = STONE_BRICK_STAIRS;
	WAXED_EXPOSED_CUT_COPPER_STAIRS = g({"stairs:stair_copperblock", "stairs:stair_stonebrick"});
	WHITE_WALL_BANNER = WHITE_WOOL;
	BLUE_WALL_BANNER = BLUE_WOOL;
	BLACK_WALL_BANNER = BLACK_CONCRETE;
	RED_WALL_BANNER = RED_WOOL;
	GREEN_WALL_BANNER = GREEN_WOOL;
	MOSSY_STONE_BRICKS = g({"default:mossycobble", "default:stonebrick"});
	DEEPSLATE = STONE;
	TUFF = STONE;
	COBBLED_DEEPSLATE = COBBLESTONE;
	WATER_CAULDRON = CAULDRON;
	WAXED_COPPER_BLOCK = g({"default:copperblock", "default:stone"});
	WAXED_EXPOSED_COPPER = g({"default:copperblock", "default:stone"});
	WAXED_EXPOSED_CHISELED_COPPER = g({"default:copperblock", "default:stone"});
	WAXED_EXPOSED_CUT_COPPER = g({"default:copperblock", "default:stone"});
	CHERRY_LOG = g({"default:aspen_tree", "default:tree"});
	CHERRY_LEAVES = g({"default:aspen_leaves", "default:leaves"});
	GRAY_CONCRETE_POWDER = g({"default:gravel", "dye:grey"});
	CYAN_TERRACOTTA = CYAN_CONCRETE;
	BLACK_WOOL = g("wool:black");
	LIGHT_GRAY_WALL_BANNER = LIGHT_GRAY_CONCRETE;
}

}
