# Resolve static transitive dependencies before normal package discovery.
find_package(PkgConfig REQUIRED)

function(fm_appimage_library package name)
    pkg_check_modules(FM_PC QUIET "${package}")
    set(CMAKE_FIND_LIBRARY_SUFFIXES .a .so)
    find_library(primary NAMES "${name}" HINTS ${FM_PC_LIBRARY_DIRS} NO_CACHE REQUIRED)
    set(dependencies)
    set(complete ${FM_PC_FOUND})
    if(primary MATCHES "\\.a$")
        foreach(lib IN LISTS FM_PC_STATIC_LIBRARIES)
            if(lib STREQUAL name)
                continue()
            endif()
            unset(resolved)
            find_library(resolved NAMES "${lib}" HINTS ${FM_PC_STATIC_LIBRARY_DIRS} NO_CACHE)
            if(resolved)
                list(APPEND dependencies "${resolved}")
            else()
                set(complete FALSE)
                message(STATUS "${name}: dependency ${lib} unavailable; using shared ${name}")
            endif()
        endforeach()
        if(complete)
            # Archive presence alone is insufficient: dependencies can have
            # private dependencies missing from the parent's pkg-config file.
            include(CheckCXXSourceCompiles)
            set(CMAKE_REQUIRED_LIBRARIES "-Wl,--start-group"
                "-Wl,--whole-archive" "${primary}" "-Wl,--no-whole-archive"
                ${dependencies} ${FM_PC_STATIC_LDFLAGS_OTHER} "-Wl,--end-group")
            unset(FM_ARCHIVE_LINKS CACHE)
            check_cxx_source_compiles("int main() { return 0; }" FM_ARCHIVE_LINKS)
            if(NOT FM_ARCHIVE_LINKS)
                # Keep the primary archive if shared dependencies provide the
                # missing private dependency closure.
                set(CMAKE_FIND_LIBRARY_SUFFIXES .so .a)
                set(dependencies)
                foreach(lib IN LISTS FM_PC_STATIC_LIBRARIES)
                    if(lib STREQUAL name)
                        continue()
                    endif()
                    unset(resolved)
                    find_library(resolved NAMES "${lib}" HINTS ${FM_PC_STATIC_LIBRARY_DIRS} NO_CACHE REQUIRED)
                    list(APPEND dependencies "${resolved}")
                endforeach()
                set(CMAKE_REQUIRED_LIBRARIES "-Wl,--start-group"
                    "-Wl,--whole-archive" "${primary}" "-Wl,--no-whole-archive"
                    ${dependencies} ${FM_PC_STATIC_LDFLAGS_OTHER} "-Wl,--end-group")
                unset(FM_ARCHIVE_LINKS CACHE)
                check_cxx_source_compiles("int main() { return 0; }" FM_ARCHIVE_LINKS)
            endif()
            if(NOT FM_ARCHIVE_LINKS)
                set(complete FALSE)
                message(STATUS "${name}: static dependency link failed; using shared ${name}")
            endif()
        endif()
        if(NOT complete)
            set(CMAKE_FIND_LIBRARY_SUFFIXES .so)
            unset(primary)
            find_library(primary NAMES "${name}" HINTS ${FM_PC_LIBRARY_DIRS} NO_CACHE REQUIRED)
            set(dependencies)
        endif()
    endif()
    foreach(variable IN LISTS ARGN)
        set(${variable} "${primary}" CACHE FILEPATH "AppImage library selection" FORCE)
    endforeach()
    if(name STREQUAL "SDL2")
        if(primary MATCHES "\\.a$")
            set(USE_SDL2_STATIC ON CACHE BOOL "AppImage SDL selection" FORCE)
        else()
            set(USE_SDL2_STATIC OFF CACHE BOOL "AppImage SDL selection" FORCE)
        endif()
    endif()
    if(primary MATCHES "\\.a$")
        set_property(GLOBAL APPEND PROPERTY FM_APPIMAGE_LINK_LIBS
            "${primary}" ${dependencies} ${FM_PC_STATIC_LDFLAGS_OTHER})
    endif()
    message(STATUS "AppImage ${name}: ${primary}")
endfunction()

fm_appimage_library(libcurl curl CURL_LIBRARY CURL_LIBRARY_RELEASE CURL_LIBRARY_DEBUG)
fm_appimage_library(freetype2 freetype FREETYPE_LIBRARY_RELEASE FREETYPE_LIBRARY_DEBUG FREETYPE_LIBRARY)
fm_appimage_library(sdl2 SDL2)

# Append dependency closure only to the application, not bundled build tools.
function(fm_appimage_link)
    # The deferred root call links targets defined in src/.
    cmake_policy(PUSH)
    cmake_policy(SET CMP0079 NEW)
    get_property(libraries GLOBAL PROPERTY FM_APPIMAGE_LINK_LIBS)
    foreach(target freeminer freeminerserver)
        if(TARGET ${target} AND libraries)
            target_link_libraries(${target} "-Wl,--start-group" ${libraries} "-Wl,--end-group")
        endif()
    endforeach()
    cmake_policy(POP)
endfunction()
cmake_language(DEFER CALL fm_appimage_link)
